version: "3.8"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
    - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "8080:8080"
volumes:
  data: