version: "3.8"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go-rest-api
    ports:
    - "5432:5432"
    volumes:
    - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "8080:8080"
volumes:
  data: